/**
 * THE WORD DECK FOR WORTDUELL — nouns whose article a learner must know.
 *
 * Deliberately a bundled list rather than a database table or an AI call: a
 * duel has to be instant and free to run, the answers must be certain, and a
 * tutor should never have to author content for it to work. Every entry is a
 * common noun with one unambiguous article. Words whose gender differs by
 * region or meaning (der/das Joghurt, der/die Teil…) are left out on purpose —
 * a game that marks a correct answer wrong teaches the wrong thing.
 *
 * Grouped by the CEFR level a learner is likely to meet the word at. C1/C2
 * students play the B2 deck (see deckLevelOf in lib/duel.ts).
 *
 * Format: [article, noun, English].
 */

export type Article = "der" | "die" | "das";
export type DeckEntry = readonly [Article, string, string];

export const DECK: Record<"A1" | "A2" | "B1" | "B2", readonly DeckEntry[]> = {
  A1: [
    ["der", "Tisch", "table"],
    ["der", "Stuhl", "chair"],
    ["der", "Apfel", "apple"],
    ["der", "Hund", "dog"],
    ["der", "Brief", "letter"],
    ["der", "Käse", "cheese"],
    ["der", "Kaffee", "coffee"],
    ["der", "Bruder", "brother"],
    ["der", "Freund", "friend"],
    ["der", "Garten", "garden"],
    ["der", "Vater", "father"],
    ["die", "Tür", "door"],
    ["die", "Katze", "cat"],
    ["die", "Mutter", "mother"],
    ["die", "Schule", "school"],
    ["die", "Straße", "street"],
    ["die", "Uhr", "clock"],
    ["die", "Tasche", "bag"],
    ["die", "Lampe", "lamp"],
    ["die", "Woche", "week"],
    ["die", "Stadt", "city"],
    ["die", "Familie", "family"],
    ["die", "Zeitung", "newspaper"],
    ["das", "Haus", "house"],
    ["das", "Buch", "book"],
    ["das", "Kind", "child"],
    ["das", "Auto", "car"],
    ["das", "Wasser", "water"],
    ["das", "Brot", "bread"],
    ["das", "Fenster", "window"],
    ["das", "Bett", "bed"],
    ["das", "Mädchen", "girl"],
    ["das", "Zimmer", "room"],
    ["das", "Essen", "food"],
    ["das", "Geld", "money"],
    ["das", "Handy", "mobile phone"],
  ],
  A2: [
    ["der", "Bahnhof", "train station"],
    ["der", "Flughafen", "airport"],
    ["der", "Urlaub", "holiday"],
    ["der", "Schlüssel", "key"],
    ["der", "Termin", "appointment"],
    ["der", "Arzt", "doctor"],
    ["der", "Computer", "computer"],
    ["der", "Regen", "rain"],
    ["der", "Sommer", "summer"],
    ["der", "Supermarkt", "supermarket"],
    ["der", "Fahrplan", "timetable"],
    ["die", "Rechnung", "bill"],
    ["die", "Wohnung", "flat"],
    ["die", "Küche", "kitchen"],
    ["die", "Arbeit", "work"],
    ["die", "Reise", "journey"],
    ["die", "Brücke", "bridge"],
    ["die", "Kreuzung", "crossroads"],
    ["die", "Haltestelle", "stop"],
    ["die", "Einladung", "invitation"],
    ["die", "Erkältung", "cold"],
    ["die", "Apotheke", "pharmacy"],
    ["das", "Krankenhaus", "hospital"],
    ["das", "Restaurant", "restaurant"],
    ["das", "Frühstück", "breakfast"],
    ["das", "Gepäck", "luggage"],
    ["das", "Ticket", "ticket"],
    ["das", "Gleis", "platform"],
    ["das", "Hotel", "hotel"],
    ["das", "Büro", "office"],
    ["das", "Gemüse", "vegetables"],
    ["das", "Ergebnis", "result"],
    ["das", "Wetter", "weather"],
    ["das", "Geschenk", "gift"],
    ["das", "Gespräch", "conversation"],
  ],
  B1: [
    ["der", "Lebenslauf", "CV"],
    ["der", "Vertrag", "contract"],
    ["der", "Nachbar", "neighbour"],
    ["der", "Gedanke", "thought"],
    ["der", "Vorschlag", "suggestion"],
    ["der", "Unterschied", "difference"],
    ["der", "Beruf", "profession"],
    ["der", "Abschluss", "degree"],
    ["der", "Einfluss", "influence"],
    ["der", "Vorteil", "advantage"],
    ["der", "Nachteil", "disadvantage"],
    ["der", "Zweck", "purpose"],
    ["die", "Bewerbung", "application"],
    ["die", "Meinung", "opinion"],
    ["die", "Erfahrung", "experience"],
    ["die", "Umwelt", "environment"],
    ["die", "Gesellschaft", "society"],
    ["die", "Ausbildung", "training"],
    ["die", "Verbindung", "connection"],
    ["die", "Entscheidung", "decision"],
    ["die", "Verantwortung", "responsibility"],
    ["die", "Gelegenheit", "opportunity"],
    ["die", "Geschwindigkeit", "speed"],
    ["das", "Angebot", "offer"],
    ["das", "Ziel", "goal"],
    ["das", "Interesse", "interest"],
    ["das", "Verhältnis", "relationship"],
    ["das", "Gehalt", "salary"],
    ["das", "Problem", "problem"],
    ["das", "Beispiel", "example"],
    ["das", "Programm", "programme"],
    ["das", "Praktikum", "internship"],
    ["das", "Studium", "studies"],
    ["das", "Mitglied", "member"],
    ["das", "Thema", "topic"],
    ["das", "Ereignis", "event"],
  ],
  B2: [
    ["der", "Wettbewerb", "competition"],
    ["der", "Zusammenhang", "connection, context"],
    ["der", "Anspruch", "claim"],
    ["der", "Fortschritt", "progress"],
    ["der", "Verbraucher", "consumer"],
    ["der", "Gegensatz", "contrast"],
    ["der", "Ausgleich", "balance, compensation"],
    ["der", "Zustand", "condition"],
    ["der", "Verlauf", "course"],
    ["der", "Eindruck", "impression"],
    ["der", "Standpunkt", "point of view"],
    ["der", "Überblick", "overview"],
    ["die", "Entwicklung", "development"],
    ["die", "Herausforderung", "challenge"],
    ["die", "Voraussetzung", "prerequisite"],
    ["die", "Wirtschaft", "economy"],
    ["die", "Gleichberechtigung", "equality"],
    ["die", "Auswirkung", "effect"],
    ["die", "Fähigkeit", "ability"],
    ["die", "Genehmigung", "permit"],
    ["die", "Behörde", "authority"],
    ["die", "Forschung", "research"],
    ["die", "Gewohnheit", "habit"],
    ["das", "Verhalten", "behaviour"],
    ["das", "Bewusstsein", "awareness"],
    ["das", "Vorhaben", "plan"],
    ["das", "Ausmaß", "extent"],
    ["das", "Verfahren", "procedure"],
    ["das", "Vermögen", "assets"],
    ["das", "Zeugnis", "certificate"],
    ["das", "Bedürfnis", "need"],
    ["das", "Gleichgewicht", "balance"],
    ["das", "Einkommen", "income"],
    ["das", "Missverständnis", "misunderstanding"],
  ],
};
