export const packageOptions = [
  "Language training",
  "Ausbildung (vocational training)",
  "Skilled migration",
  "Opportunity card",
  "Study and work in Germany",
  "Study route",
];

export const professionOptions = [
  "Student",
  "Unemployed / seeking work",
  "Business owner / entrepreneur",
  "Accountant / auditor",
  "Administrative assistant",
  "Agricultural worker / farmer",
  "Architect",
  "Artist / illustrator",
  "Banking / finance professional",
  "Barber / hairstylist",
  "Beautician / cosmetologist",
  "Biologist",
  "Bookkeeper",
  "Bricklayer / mason",
  "Builder / construction worker",
  "Business analyst",
  "Caregiver",
  "Carpenter / joiner",
  "Chef / cook",
  "Chemist",
  "Civil engineer",
  "Cleaner / domestic worker",
  "Clergy / religious worker",
  "Dentist",
  "Designer",
  "Doctor / physician",
  "Electrician",
  "Electrical engineer",
  "Engineer",
  "Fashion professional / tailor",
  "Film / television professional",
  "Fisher / fishery worker",
  "Flight attendant / cabin crew",
  "Geologist",
  "Graphic designer",
  "Healthcare professional",
  "Human resources professional",
  "Information technology professional",
  "IT support specialist",
  "Journalist / writer",
  "Lawyer / legal professional",
  "Lecturer / professor",
  "Logistics / supply chain professional",
  "Machine operator",
  "Machinist / metalworker",
  "Marketing / communications professional",
  "Mechanic / automotive technician",
  "Medical laboratory scientist",
  "Nurse",
  "Occupational therapist",
  "Office manager",
  "Pharmacist",
  "Photographer",
  "Plumber",
  "Police / security officer",
  "Politician / public official",
  "Primary school teacher",
  "Product manager",
  "Project manager",
  "Psychologist / counsellor",
  "Public relations professional",
  "Real estate professional",
  "Researcher / scientist",
  "Restaurant / hospitality worker",
  "Retail / sales professional",
  "Roofer",
  "Social worker",
  "Software developer / programmer",
  "Solar / renewable energy technician",
  "Special education professional",
  "Sports professional / coach",
  "Surgeon",
  "Surveyor",
  "Teacher / educator",
  "Technician",
  "Telecommunications professional",
  "Translator / interpreter",
  "Travel / tourism professional",
  "Truck driver / delivery driver",
  "Veterinarian",
  "Waiter / server",
  "Web developer",
  "Other / not listed",
];

export const nigerianStates = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Federal Capital Territory (Abuja)",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
